### ISSUE TITLE
Student / wyświetlanie informacji i ogłoszeń o kursie

### ISSUE THREAD

**Issue by estewui** [JedrzejDev/projekt-io#31]
![image](https://user-images.githubusercontent.com/48382351/82763937-6b490d80-9e0b-11ea-980f-b6fa86108cc4.png)

**Comment by JedrzejDev** [comment]
Backend nie zwraca informacji ani ogłoszeń na temat kursu - "info" to nazwa kursu co pozostawiam bez komentarza :D

**Comment by estewui** [comment]
To chyba ma zostać zmienione, mam nadzieję, że już jest :D

**Comment by Jacobsky98** [comment]
GET
**annoucements/course/<int:id_course>/**   ogłoszenia dla danego kursu

**Comment by JedrzejDev** [comment]
/user/courses/ powinno jeszcze zwracać 'info', które zawiera opis kursu

**Comment by Jacobsky98** [comment]
Ok. Dodałem
