### ISSUE TITLE
Wysyłanie wiadomości

### ISSUE THREAD

**Issue by estewui** [JedrzejDev/projekt-io#40]

**Comment by JedrzejDev** [comment]
![info](https://user-images.githubusercontent.com/31650419/83340066-296d0b00-a2d4-11ea-9a14-9e622cd16f6f.png)

**Comment by JedrzejDev** [comment]
To chyba nie do końca gotowe :D ?

**Comment by estewui** [comment]
W sumie racja xD bo aktualnie wszyscy możliwi użytkownicy wyświetlają się na liście po lewej stronie. Ale jak będzie czas to można wyświetlić tylko tych, z którymi rozmawialiśmy.
