### ISSUE TITLE
Student / obecność 

### ISSUE THREAD

**Issue by JedrzejDev** [JedrzejDev/projekt-io#49]

**Comment by JedrzejDev** [comment]
Backend powinien dla /presences/ zwracać jeszcze datę odnotowania obecności / nieobecności

**Comment by Jacobsky98** [comment]
**presences/**   _cała tabela presences_
**presence/<int:id>/**    _wiersz presences o danym id_
**presences/<int:id_course>/<int:id_student>/**    _obecności danego studenta na danym kursie_
**presences/course/<int:id_course>/**    _wszystkie obecności na danym kursie_
**presences/student/<int:id_student>/**    _wszystkie obecności danego studenta_
+ w tabeli presences jest kolumna date, automatycznie ustawiana na aktualny czas
