### ISSUE TITLE
Weryfikacja, czy dany student nie został już zapisany do danego kursu (AssingStudentPage.js)

### ISSUE THREAD

**Issue by estewui** [JedrzejDev/projekt-io#54]
Oczekiwanie na odpowiedni endpoint GET User_courses

**Comment by Jacobsky98** [comment]
**userCourse/<int:id_course>/<int:id_user>/**    _zwraca pustego JSONa jeżeli nie ma takiego wiersza w tabeli, jeżeli jest zwraca ten wiersz_
