### ISSUE TITLE
Zmiana endpointu

### ISSUE THREAD

**Issue by MWojtasik** [JedrzejDev/projekt-io#55]
Endpoint /userCourse/ zwraca id użytkownika i id kursu
Potrzebny jest endpoint - /userCourse/${id_kursu}, który zwróci użytkowników dla danego kursu. Metoda GET, w query parametrze id kursu które my podamy, a w zamian mamy dostać studentów przypisanych do danego kursu

**Comment by Jacobsky98** [comment]
Nowe GETy:
**userCourse/**   cała tabela user courses
**userCourse/user/<int:id_user>/**   kursy danego uzytkownika
**userCourse/course/<int:id_course>/**   uzytkownicy danego kursu

**Comment by MWojtasik** [comment]
userCourse/course/int:id_course/ zamiast użytkoników danego kursu zwraca:
{
        "id_user": 4,
        "id_course": 1
}
