### ISSUE TITLE
Nowy endpoint

### ISSUE THREAD

**Issue by MWojtasik** [JedrzejDev/projekt-io#60]
Potrzebny endpoint, któremu podamy id kursu i id studenta, a zwróci tablicę ocen dla poszczególnych tasków, tj:
endpoint: /task?id_course=1&id_student=3
response: [ {task: 1, ocena: 2, info: "costam", reszta}, {task: 2, ocena: 2, info: "costam2", reszta} ,...]

**Comment by Jacobsky98** [comment]
Jest już coś takiego albo podobnego.
path('grades/', GradeAPIView.as_view()),
    path('grade/<int:id>/', GradeAPIView.as_view()),
    path('grades/taskStudent/<int:id_task>/<int:id_student>/', GradeAPIView.as_view()),
    grades/courseStudent/<int:id_course>/<int:id_student>/

**Comment by MWojtasik** [comment]
okej, dzięki 🗡️
